title: Anglo-Chinese School (Junior)
url: ""
favicon: /images/bottom-logo (1).png
colors:
  primary-color: "#153965"
  secondary-color: "#948d1b"
  media-colors:
    - title: media-color-one
      color: "#153965"
    - title: media-color-two
      color: "#153965"
    - title: media-color-three
      color: "#153965"
    - title: media-color-four
      color: "#153965"
    - title: media-color-five
      color: "#153965"
description: Anglo-Chinese School (Junior)
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://moe-acsj-staging.netlify.app
prod: https://moe-acsj-prod.netlify.app
shareicon: /images/school_crest.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
